### ISSUE TITLE
Licence model not Opensource

### ISSUE THREAD

**Issue by signalwerk** [matthewepler/ReCode_Project#7]
Wow! I got across this really cool project you kicked off! Thanks a lot for your effort an all that work! Already  some awesome translations in there! Unfortunately in the processing sketch files there is always the Creative Commons license CC BY-SA 3.0 disclaimer. 

Of course I really like the CC licence and personally I try to publish as many intelectual property as possible under a fee licence. But unfortunately the CC-Licence is not a Software License and doesn't cover the needs for code. 

Even cc agrees on that as you can see in their [FAQ](http://wiki.creativecommons.org/FAQ#Can_I_use_a_Creative_Commons_license_for_software.3F)

If you still want to stick to a CC then the only Licence could be [CC0](http://wiki.creativecommons.org/CC0_FAQ#May_I_apply_CC0_to_computer_software.3F_If_so.2C_is_there_a_recommended_implementation.3F)
But because the [Open Source Initiative](http://opensource.org) didn't accept that licence as [open](http://opensource.org/faq#cc-zero) it is still not a good decision. 

The current code is [processing](http://processing.org/) code (Java) and maybe someone would like to use it in [processing.js](http://processingjs.org/) (JavaScript). Therefore is also the debate with [GPL](http://opensource.org/licenses/GPL-3.0) or [LGPL](http://opensource.org/licenses/LGPL-3.0) because in JS it's not compiled and you never know what kind of Licence applies to the rest of the code. That's the reason most JS libraries do [BSD](http://opensource.org/licenses/BSD-3-Clause), [MIT](http://opensource.org/licenses/MIT) or dual-licensing with [BSD](http://opensource.org/licenses/BSD-3-Clause)/[MIT](http://opensource.org/licenses/MIT)&[GPL](http://opensource.org/licenses/GPL-3.0). Some examples:
- [jquery](http://jquery.org/license/) as [MIT](http://opensource.org/licenses/MIT)
- [processing.js](http://processingjs.org/) as [MIT](http://opensource.org/licenses/MIT)
- [paper.js](http://paperjs.org/) as [MIT](http://opensource.org/licenses/MIT)

I would really like to see new sketches under a proper licence so the authors an users are save. 

Thank you for all that cool stuff out there! :cake:
Stefan Huber

**Comment by matthewepler** [comment]
Thanks so much for the insight. That is all very good to learn. What
license should we be using?

On Fri, Nov 30, 2012 at 4:02 AM, signalwerk notifications@github.comwrote:

> Wow! I got across this really cool project you kicked off! Thanks a lot
> for your effort an all that work! Already some awesome translations in
> there! Unfortunately in the processing sketch files there is always the
> Creative Commons license CC BY-SA 3.0 disclaimer.
> 
> Of course I really like the CC licence and personally I try to publish as
> many intelectual property as possible under a fee licence. But
> unfortunately the CC-Licence is not a Software License and doesn't cover
> the needs for code.
> 
> Even cc agrees on that as you can see in their FAQhttp://wiki.creativecommons.org/FAQ#Can_I_use_a_Creative_Commons_license_for_software.3F
> 
> If you still want to stick to a CC then the only Licence could be CC0http://wiki.creativecommons.org/CC0_FAQ#May_I_apply_CC0_to_computer_software.3F_If_so.2C_is_there_a_recommended_implementation.3F
> But because the Open Source Initiative http://opensource.org didn't
> accept that licence as open http://opensource.org/faq#cc-zero it is
> still not a good decision.
> 
> The current code is processing http://processing.org/ code (Java) and
> maybe someone would like to use it in processing.jshttp://processingjs.org/(JavaScript). Therefore is also the debate with
> GPL http://opensource.org/licenses/GPL-3.0 or LGPLhttp://opensource.org/licenses/LGPL-3.0because in JS it's not compiled and you never know what kind of Licence
> applies to the rest of the code. That's the reason most JS libraries do
> BSD http://opensource.org/licenses/BSD-3-Clause, MIThttp://opensource.org/licenses/MITor dual-licensing with
> BSD http://opensource.org/licenses/BSD-3-Clause/MIThttp://opensource.org/licenses/MIT
> &GPL http://opensource.org/licenses/GPL-3.0. Some examples:
> - jquery http://jquery.org/license/ as MIThttp://opensource.org/licenses/MIT
> - processing.js http://processingjs.org/ as MIThttp://opensource.org/licenses/MIT
> - paper.js http://paperjs.org/ as MIThttp://opensource.org/licenses/MIT
> 
> I would really like to see new sketches under a proper licence so the
> authors an users are save.
> 
> Thank you for all that cool stuff out there! [image: :cake:]
> Stefan Huber
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/matthewepler/ReCode_Project/issues/7.

## 

Matthew Epler
http://mepler.com

**Comment by signalwerk** [comment]
In the end it's up to you – but if you would like to have an open source licence what you can safely use in processing.js you should go for [BSD](http://opensource.org/licenses/BSD-3-Clause) or [MIT](http://opensource.org/licenses/MIT). MIT is bit more common.

**Comment by quinkennedy** [comment]
The next question is, how do we go about migrating our code to whichever new license is decided on? Is it as simple as changing the license referenced in the source? I assume each translation/experiment author would have to do this individually and send a pull request?

**Comment by signalwerk** [comment]
Indeed; this is a much bigger case and I hope you will not run into bigger troubles. Because you are at the very beginning it's still possible to solve that problem. I'd suggest you use this Issue-Report as a Umbrella-Issue (meaning you consolidate all related pull requests here, so people can see why and what)

I'd do it like that
- branch the master
- fix the headers of your files 
- push the fixed headers to he new branch
- add a new comment here with the commit-url so other people can see your effort
- ask the contributors you know to patch their code (according to your code-example) and send you pull requests
- migrate the pull requests to the new branch and note here, so other people can see others effort as well
- once you have everything together you migrate the new branch to the master

When you do it like that you easily see where you miss the new patches. 
When people don't do patches and just send you e-mails please put the mail in the commit-note. (at least something)
If people don't respond: shit! Then it's a mine-trap for other users to use the code and we have to figure out what next...  

If you'd like me to help; I can offer to get in contact with the people (a list would help) and/or to suggest a header-file here.

**Comment by signalwerk** [comment]
Just came across by accident: https://github.com/matthewepler/ReCode_Project/commit/9d17603a98c60c20625cfd9086ac951acccc7526

Here was already a MIT compatible License.

**Comment by K0F** [comment]
:) yeah, with a copyleft there are less questions how do you mean it, but I accept an argument that anyone can "close" your code afterwards..

There is a whole range of GPL-compatible free software licenses commented by Richard Stallman http://www.gnu.org/licenses/license-list.html, which represents one point of view I would agree with, on the other hand.. I would suggest to listen to Lawrence Lessig's lecture here http://randomfoo.net/oscon/2002/lessig/free.html, who argues that any copyright restrict for further use..

**Comment by signalwerk** [comment]
Thanks for your input! Personally I like BSD/MIT-Licenses more than the (L)GPL because of the fact that everyone can do what they like to do with it. That's for me a good definition of open and free. But at the other hand I also understand the GNU-/LINUX-/GPL-Guys. When I look back for the last 5 years for me some astonishing open projects under BSD/MIT became big because of the fact corporations were able to use these project in their closed-environment but gave back a lot of code. Just think of LLVM or JavaScript engine V8 (witch powers node.js and chrome). But I know we should not have an argument over licenses. It's more a religion than a fact. The only thing I'm saying here: Creative Commons license CC BY-SA 3.0 is not a software license and the authors should come to a agreement of a software license. Because I'm just rocking the boat and didn't contribute – I'm anyway out :speak_no_evil: :see_no_evil: :hear_no_evil:

**Comment by quinkennedy** [comment]
I'll put in a second vote for BSD/MIT

**Comment by K0F** [comment]
I agree that GPL-like licences are restrictive and applies very fascistic rules to determine software freedom.  Paradoxically people who fights for software freedom advocate the most restrictive rules, it is a systematic approach directed against the conception of a intellectual property in general. Of course, applicability of such concept has been discussed widely in the past, the point is that, the person who decide to keep his knowledge open, forces any his followers to act the very same way.. it is not practical but what is even more essential question.. can we call this freedom at all?

So, what is left, the other concept is to act completely a-systematically and deny the whole idea by copyleft-ing own work. I am just afraid that, you have even probably no right to act like this, as far as you are using software containing any previous licence, where is your work without it?

The point is just that, the whole conception of so called intellectual property is pure bullshit.. and the grave of the one who first has this heretical idea should be ceremonially defiled. ))

p.s.: one vote for BSD/MIT (if any)

**Comment by signalwerk** [comment]
bon mot! I think it's always like [standing on the shoulders of giants](http://en.wikipedia.org/wiki/Standing_on_the_shoulders_of_giants). But what kind of giant do we like to stand on?!

Well – I think I'll hack a cheap translation tomorrow so I also have a vote  #yay 
I'll include a BSD/MIT header

**Comment by matthewepler** [comment]
Thanks everybody for the input. Very informative and I'm grateful to have it. I've been doing a lot of thinking about how to move forward with the project and make everything more robust/easier. I agree this is a problem that should be fixed immediately.

The spirit and text behind of the project has always included the mandate that all code be made available for use to anyone while retaining attribution to the author. Given that the current licence does not do that, every piece should be changed to reflect the intent of the project. 

I don't want to overstep any boundaries, but given the nature of this problem, I think it would be most efficient if I just replaced any CC licence with the MIT licence, with an explanation in the commit as well as a few sentences asking people to contact me directly if they are opposed to the change. Does that sound unreasonable?

As of now, I have avoided user sessions and thus have no contact information other than the gitHub accounts for those that have them, but not everyone does. So there is no full or reliable contact list as of now.

Please respond here for your thoughts on the direct editing of the code by myself or feel free to suggest another approach. I will start another Issue thread to discuss the future of the project and look forward to any responses there as well.

**Comment by signalwerk** [comment]
Hi matthewepler 
I don't know but just to overwrite the licence by yourself doesn't sound good to me. Imagine someone copys the code to some other project and in the end the original author starts making troubles. I hope it's unlikely but I'd rather delete or leave the old code before just overwrite the copyright by yourself.

Did a pull with a mit/gpl3 license : https://github.com/matthewepler/ReCode_Project/pull/12

**Comment by signalwerk** [comment]
As seen here: https://github.com/matthewepler/ReCode_Project/pull/11 
First migration of code. Maybe would be good to have a header-template so we could standardize the headers across the project. Feel free to overwrite my header. Just keep the license types (not the look/wording). Thx.

**Comment by K0F** [comment]
Indeed header-template would be great, it can prevent some future misunderstanding.

> Imagine someone copys the code to some other project and in the end the original author starts making troubles.

Sure, it may be true.. but, hopefully not in our case ;)

**Comment by signalwerk** [comment]
yea! more pull requests: https://github.com/quinkennedy/ReCode_Project/commit/4d483d566c6f0ef17c0c73ea5901fab2c7260950
still with the license issue. 
@matthewepler MIT? You're the master.
Are you doing a Header-Template, so the fresh pull-requests can change to that header before merge? thx a lot!

**Comment by quinkennedy** [comment]
this whole license thing is really a pain in the butt. I can't speak for anyone else, but when I get down to it, I don't care about the license. I just want to recreate and have a personal exploration of these artworks. I also love the idea of sharing the code as a learning resource and inspirational jumping-off point. I would rather not worry about licenses or anything, but todays culture has this necessity to slap some sort of license on everything, so.. whatever, just give me a header template and maybe I'll use it.

Ultimately, I feel like each individual developer should decide on their license if they care. The idea of one license for the entire repo is nobel, but is it necessary? I feel like most developers won't care too much about the license as long as it is in the spirit of the ReCode project.

so I would suggest just putting the preferred header template on github or on the site somewhere, and then contacting all the developers you can to ask them to update their license if they want. Then wash your hands and worry about other stuff.

**Comment by K0F** [comment]
@quinkennedy ..well said, I agree with you completely. I feel spirit of ReCode mainly as cultural / artist point of view which is morally pure, not any damn calculative lawyer's perspective.

**Comment by signalwerk** [comment]
right. @K0F made a MIT header in his last pull request (https://github.com/matthewepler/ReCode_Project/pull/11) and I did a MIT/GPL3 (https://github.com/matthewepler/ReCode_Project/pull/12) reference. I'd say if no other people come up with other headers we go for @K0F. It's the standard MIT head you can see in many projects.

**Comment by matthewepler** [comment]
Thanks so much everyone! Sorry I've been off the radar. I'm finishing up
final projects at school and have been unable to devote any time to ReCode
Project. I should be back next week. Thanks again. We've got some good
things coming.

Matt

On Wed, Dec 5, 2012 at 4:38 PM, Stefan Huber notifications@github.comwrote:

> right. @K0F https://github.com/K0F made a MIT header in his last pull
> request (#11 https://github.com/matthewepler/ReCode_Project/issues/11)
> and I did a MIT/GPL3 (#12https://github.com/matthewepler/ReCode_Project/issues/12)
> reference. I'd say if no other people come up with other headers we go for
> @K0F https://github.com/K0F. It's the standard MIT head you can see in
> many projects.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/matthewepler/ReCode_Project/issues/7#issuecomment-11061767.

## 

Matthew Epler
http://mepler.com

**Comment by signalwerk** [comment]
just to give an update: right now all pending pull requests would agree to the current MIT-License of @K0F. I will continue to patch all pull-requests to the current MIT-License. As soon as @matthewepler merges one patch with the MIT-License I'll also do a small example-header and a short description how to use it.

**Comment by matthewepler** [comment]
Hi all,

I made changes to the license on the site. Please check your contributions and let me know if something isn't right. I'm sorry I couldn't do this more democratically this time. It will be much easier to operate in an open way if I can contact everyone. 

Please send me your email address so I can add you to the core contributor list. It will make communication much smoother.

Thanks and happy holidays!

Matt Epler
